//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int Id { get; set; }
        public Nullable<int> FileStatus_Id { get; set; }
        public Nullable<int> CaseId { get; set; }
        public string FullName { get; set; }
        public string SubscriptionCode { get; set; }
    
        public virtual FileStatu FileStatu { get; set; }
    }
}
